# SPDX-FileCopyrightText: 2021 Arthur Breitman

# SPDX-License-Identifier: LicenseRef-MIT-Arthur-Breitman

- message:
  - name: Redundant build-depends entry
  - depends:
    - base-noprelude
    - morley-prelude
