# SPDX-FileCopyrightText: 2021 Arthur Breitman
# SPDX-License-Identifier: LicenseRef-MIT-Arthur-Breitman

resolver: haskell/snapshot.yaml

packages:
  - haskell

# See extra-deps in haskell/snapshot.yaml
