# SPDX-FileCopyrightText: 2021 Arthur Breitman
# SPDX-License-Identifier: LicenseRef-MIT-Arthur-Breitman

env:
  FETCH_CONTRACT: >-
    mkdir -p haskell/test/
    && buildkite-agent artifact download ligo-out/storage_default.tz haskell/test/
    && buildkite-agent artifact download ligo-out/segmented_cfmm_default.tz haskell/test/

steps:
  - label: hlint
    commands:
    - nix run -f ci.nix pkgs.hlint -c
        ./scripts/lint.sh

  - label: reuse lint
    commands:
    - nix run -f ci.nix pkgs.reuse -c
        reuse lint

  - label: check trailing whitespace
    commands:
    - .buildkite/check-trailing-whitespace.sh

  - label: xrefcheck
    commands:
    - nix run -f ci.nix xrefcheck -c xrefcheck
    retry:
      automatic:
        limit: 1

  - label: check cabal files
    commands:
    - nix run -f ci.nix stack2cabal pkgs.diffutils -c ./scripts/ci/validate-cabal-files.sh

  - label: build-ligo
    key: build-ligo
    commands:
      - nix-build ci.nix -A build-ligo -o ./ligo-out/
    artifact_paths:
      - ligo-out/*

  - label: build-haskell
    key: build-haskell
    depends_on:
      - build-ligo
    commands:
    - eval "$FETCH_CONTRACT"
    - nix-build ci.nix -A all-components

  - label: check typescript api
    depends_on:
      - build-ligo
      - build-haskell
    commands:
      - nix run -f ci.nix packages.segmented-cfmm.exes.segmented-cfmm pkgs.diffutils -c ./scripts/ci/validate-typescript-api.sh


  - label: typescript-build
    depends_on:
      - build-ligo
      - build-haskell
    commands:
    - nix-build ci.nix -A build-typescript --arg release false

  - label: weeder
    depends_on: build-haskell
    commands:
    - nix-build ci.nix -A weeder-script
    - ./result

  - label: haddock
    depends_on: build-haskell
    commands:
    - nix-build ci.nix -A haddock --no-out-link
